services:
  seed.registry:
    class: 'Evotodi\SeedBundle\Core\SeedRegistry'
    public: true

  seed.seed_core_command:
    class: 'Evotodi\SeedBundle\Core\SeedCoreCommand'
    calls:
      - [ setContainer, [ '@service_container' ] ]

  seed.load_seeds_command:
    class: 'Evotodi\SeedBundle\Command\LoadSeedsCommand'
    tags:
      - {name: 'console.command'}
    parent: seed.seed_core_command
    public: true

  seed.unload_seeds_command:
    class: 'Evotodi\SeedBundle\Command\UnloadSeedsCommand'
    tags:
      - { name: 'console.command' }
    parent: seed.seed_core_command
    public: true
